# Generated by Django 4.0.5 on 2022-06-27 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(max_length=50, unique=True)),
                ('channel_url', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('follow_count', models.IntegerField(default=0)),
                ('target_channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channelstatistics', to='main.instagramchannel')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_id', models.CharField(max_length=50, unique=True)),
                ('post_url', models.CharField(max_length=100)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('post_thumbnail', models.CharField(blank=True, max_length=100, null=True)),
                ('published_at', models.DateTimeField(verbose_name='Date Published')),
                ('target_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelpost', to='main.instagramchannel')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
