# Generated by Django 4.0.5 on 2022-07-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_directmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(max_length=50, unique=True)),
                ('is_dm_sent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_comment_needed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
